/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javalab2b;

public class Library {
    public boolean someLibraryMethod() {
System.out.println("hello");




        return true;
    }
}
