/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testroll() {

        ArrayList<Integer> testArray = new ArrayList<>();
        Library rollTest = new Library();
        ArrayList<Integer> rollArr= rollTest.roll(4);

        assertEquals("Both sizes are the same", rollArr.size(),4);


    }// end testRoll()
    @Test
    public void testcontainsDuplicates() {

        Library containsDuplicatesTest = new Library();
        int []arr={1,2,1};
        assertTrue("the array has duplicate elements 'true'",containsDuplicatesTest.containsDuplicates(arr));

    }//end testcontainsDuplicates()
    @Test
    public void testcalculatingAverages() {
    Library calculatingAveragesTest = new Library();
    double expectAvg=3.0;
    int [] testArr= {2,2,5};
    assertTrue("the expected Average equal 3.0",calculatingAveragesTest.calculatingAverages(testArr) != expectAvg);
    }//end testcalculatingAverages()




    }// end class

