/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;

public class Library {
    public static ArrayList roll (int n) {
        ArrayList <Integer> rollArr=new ArrayList<>();
     for(int i=0;i<n;i++) {
        int randRoll=(int)(Math.random() * 6)+1;
        rollArr.add(randRoll);

     }// end for
        System.out.println(rollArr);
        return rollArr;
    }//end roll()
    public  boolean containsDuplicates(int []arr){
      for (int i=0;i< arr.length-1;i++){
      for (int j=i+1;j< arr.length;j++){
          if (arr[i] == arr[j]) {
              return true;
          }//end if

      }//end internal for

      }// end external for

   return false;
    }//end containsDuplicates()

public static double calculatingAverages(int []arr){
    double avg = 0.0;
    for (int i=0;i<arr.length-1;i++){
        avg+=arr[i];

    }//end for
return avg / arr.length;
}// end calculatingAverages()


    public static int arrayOfArrays(int[][] arr) {
            int sum=0;
            int avg=0;
            int lowestAvg=0;
            for (int i=0;i< arr.length;i++){
                for (int j=0;j< arr[i].length;j++){
                    sum=sum+arr[i][j];
                }//end internal for
                avg=sum/arr[i].length;
                System.out.println(sum);
                if(i==0){
                    lowestAvg=avg;
                }// end if
                if(avg<lowestAvg){
                    lowestAvg=avg;
                }// end if
                sum=0;
                avg=0;
            }// end external for
            System.out.println(lowestAvg);
            return lowestAvg;
        }//end arrayOfArrays()
}// end class
